version: '3.8'

services:
  humhub:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your updated Dockerfile with PHP 8.2 and mailers is in the same directory
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
      HUMHUB_DIRECTORY: "/var/www/html"
      MAILER_DSN: "sendmail://default" # Use Symfony Mailer's sendmail transport
      REDIS_HOST: "redis"

  mysql:
    image: mysql:5.7  # You might want to consider updating MySQL to a compatible version with PHP 8.2
    environment:
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
    volumes:
      - "humhub_db_data:/var/lib/mysql"

  redis:
    image: redis

volumes:
  humhub_db_data:
