version: '3.8'

services:
  humhub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
      HUMHUB_DIRECTORY: "/var/www/html"
      SMTP_HOST: "smtp.mailtrap.io"
      SMTP_PORT: "2525"
      REDIS_HOST: "redis"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
    volumes:
      - humhub_db_data:/var/lib/mysql

  redis:
    image: redis

volumes:
  humhub_data:
  humhub_db_data:
