version: '3.8'

services:
  humhub:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      MYSQL_HOST: "mysql_humhub"
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
      HUMHUB_DIRECTORY: "/var/www/html"
      MAILER_DSN: "sendmail://default"
    volumes:
      - humhub_files:/var/www/html
    networks:
      - humhub_network

  mysql_humhub:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
    volumes:
      - humhub_db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./humhub.conf:/etc/nginx/conf.d/humhub.conf
      - nginx_cert:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - humhub_network

  certbot:
    image: certbot/certbot
    volumes:
      - nginx_cert:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"

networks:
  humhub_network:
    driver: bridge

volumes:
  humhub_files:
    driver: local
  humhub_db_data:
    driver: local
  nginx_cert:
    driver: local
