version: '3.8'

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: "humhub"
      MYSQL_USER: "humhub"
      MYSQL_PASSWORD: "password"
    volumes:
      - humhub_db_data:/var/lib/mysql
    networks:
      - humhub_network

volumes:
  humhub_db_data:
    driver: local

networks:
  humhub_network:
    driver: bridge
