name: Codacy Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-coverage:
    name: Codacy Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t humhub-docker -f src/Dockerfile .

      - name: Run Docker container
        run: |
          docker run --name humhub-docker -d humhub-docker
          docker exec humhub-docker composer install
          docker exec humhub-docker ./vendor/bin/phpunit --migrate-configuration
          docker exec humhub-docker ./vendor/bin/phpunit --coverage-clover=/tests/coverage.xml

      - name: Copy coverage report
        run: docker cp humhub-docker:/tests/coverage.xml coverage.xml

      - name: Upload coverage reports to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            -r coverage.xml

      - name: Clean up
        run: docker rm -f humhub-docker
