# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, runs tests, generates a coverage report,
# performs a Codacy security scan, and integrates the results with GitHub
# Advanced Security for code scanning. For more information on the Codacy
# security scan action usage and parameters, see
# https://github.com/codacy/codacy-coverage-reporter-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-coverage-reporter-action.

name: Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install codacy-analysis-cli from GitHub
        run: |
          curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
          cd codacy-analysis-cli-* && sudo make install

      # Example: Run Codacy Analysis CLI for Dockerfile linting
      - name: Run Codacy Analysis for Dockerfile
        run: |
          codacy-analysis-cli analyze --tool hadolint --format sarif --output results_dockerfile.sarif src/Dockerfile

      # Example: Run Codacy Analysis CLI for general code analysis (replace with your actual commands)
      - name: Run Codacy Analysis for codebase
        run: |
          codacy-analysis-cli analyze --tool <tool> --format sarif --output results_codebase.sarif <path_to_code>

  upload-sarif:
    name: Upload SARIF results
    runs-on: ubuntu-latest
    needs: codacy-security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Example: Upload Dockerfile SARIF results to GitHub
      - name: Upload Dockerfile SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_dockerfile.sarif

      # Example: Upload codebase SARIF results to GitHub
      - name: Upload codebase SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_codebase.sarif
