# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, runs tests, generates a coverage report,
# performs a Codacy security scan, and integrates the results with GitHub
# Advanced Security for code scanning. For more information on the Codacy
# security scan action usage and parameters, see
# https://github.com/codacy/codacy-coverage-reporter-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-coverage-reporter-action.

name: Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install codacy-analysis-cli from GitHub
        run: |
          curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
          cd codacy-analysis-cli-* && sudo make install

      - name: Run Hadolint action for Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Dockerfile
          format: sarif
        id: hadolint

      - name: Save Hadolint results
        run: echo '${{ steps.hadolint.outputs.sarif }}' > results_dockerfile.sarif

      - name: Install docker-compose-validator
        run: |
          pip install docker-compose-validator

      - name: Run docker-compose-validator
        working-directory: src
        run: |
          docker-compose-validator docker-compose.yml > ../results_docker-compose.json

      - name: Convert docker-compose JSON to SARIF
        run: |
          npm install -g json2sarif
          json2sarif -i ../results_docker-compose.json -o results_docker-compose.sarif

  upload-sarif:
    name: Upload SARIF results
    runs-on: ubuntu-latest
    needs: codacy-security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Dockerfile SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_dockerfile.sarif

      - name: Upload docker-compose SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_docker-compose.sarif
