name: Codacy Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-coverage:
    name: Codacy Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t humhub-docker -f src/Dockerfile .

      - name: Run Docker container
        id: run_container
        run: |
          docker run --name humhub-docker -d humhub-docker || echo "Container start failed"

      - name: Check container status and logs (if failure)
        if: steps.run_container.outputs.container == "failed"
        run: |
          docker ps -a
          docker logs humhub-docker

      - name: Install dependencies and run tests
        if: success() || steps.run_container.outputs.container != "failed"
        run: |
          docker exec humhub-docker composer install || echo "Composer install failed"
          docker exec humhub-docker ./vendor/bin/phpunit --migrate-configuration || echo "PHPUnit configuration migration failed"
          docker exec humhub-docker ./vendor/bin/phpunit --coverage-clover=/tests/coverage.xml || echo "PHPUnit tests failed"

      - name: Copy coverage report
        if: success() || steps.run_container.outputs.container != "failed"
        run: docker cp humhub-docker:/tests/coverage.xml coverage.xml || echo "Failed to copy coverage report"

      - name: Upload coverage reports to Codacy
        if: success() || steps.run_container.outputs.container != "failed"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml || echo "Failed to upload coverage report"

      - name: Clean up
        run: docker rm -f humhub-docker || echo "Failed to clean up container"
