# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, runs tests, generates a coverage report,
# performs a Codacy security scan, and integrates the results with GitHub
# Advanced Security for code scanning. For more information on the Codacy
# security scan action usage and parameters, see
# https://github.com/codacy/codacy-coverage-reporter-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-coverage-reporter-action.

name: Codacy Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-coverage:
    name: Codacy Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP and dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpunit

      - name: Run PHPUnit with coverage
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            -r coverage.xml
