# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, runs tests, generates a coverage report,
# performs a Codacy security scan, and integrates the results with GitHub
# Advanced Security for code scanning. For more information on the Codacy
# security scan action usage and parameters, see
# https://github.com/codacy/codacy-coverage-reporter-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-coverage-reporter-action.

name: Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis for Dockerfile
        run: |
          codacy-analysis-cli analyze --file src/Dockerfile --format sarif --output results_dockerfile.sarif
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Run Codacy Analysis for docker-compose.yml
        run: |
          codacy-analysis-cli analyze --file src/docker-compose.yml --format sarif --output results_docker-compose.sarif
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  upload-sarif:
    name: Upload SARIF results
    runs-on: ubuntu-latest
    needs: codacy-security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Dockerfile SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_dockerfile.sarif

      - name: Upload docker-compose SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_docker-compose.sarif

      - name: Upload docker-compose SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_docker-compose.sarif
