# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, runs tests, generates a coverage report,
# performs a Codacy security scan, and integrates the results with GitHub
# Advanced Security for code scanning. For more information on the Codacy
# security scan action usage and parameters, see
# https://github.com/codacy/codacy-coverage-reporter-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-coverage-reporter-action.

name: Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '43 23 * * 5'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Codacy Analysis CLI
        run: |
          sudo apt-get update && sudo apt-get install -y make
          curl -L https://github.com/codacy/codacy-analysis-cli/releases/download/3.0.0/codacy-analysis-cli-3.0.0-linux-x86_64.tar.gz | tar xvz
          sudo mv codacy-analysis-cli-3.0.0/bin/codacy-analysis-cli /usr/local/bin/
          codacy-analysis-cli --version  # Verify installation

      - name: Create coverage directory (ensure it exists)
        run: mkdir -p ${{ github.workspace }}/tests/coverage

      - name: Run tests and generate coverage reports
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace codacy/codacy-analysis-cli:stable analyze --directory /workspace/src --format sarif --output /workspace/tests/coverage/results_dockerfile.sarif

      - name: Upload coverage reports to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          codacy-coverage-reporter report -l <format> -r ${{ github.workspace }}/tests/coverage/results_dockerfile.sarif

  upload-sarif:
    name: Upload SARIF results
    runs-on: ubuntu-latest
    needs: codacy-security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create coverage directory (ensure it exists)
        run: mkdir -p ${{ github.workspace }}/tests/coverage

      - name: List files in coverage directory (debugging step)
        run: ls -al ${{ github.workspace }}/tests/coverage

      - name: Wait for SARIF file to be created
        run: |
          echo "Waiting for SARIF file to be created..."
          sleep 10

      # Upload Dockerfile SARIF results to GitHub
      - name: Upload Dockerfile SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/tests/coverage/results_dockerfile.sarif

      # Upload codebase SARIF results to GitHub
      - name: Upload codebase SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/tests/coverage/results_codebase.sarif
