name: Hadolint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '25 8 * * 6'

permissions:
  contents: read

jobs:
  hadolint_linux_dockerfile:
    name: Run hadolint scanning for Linux Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint for Linux Dockerfile
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./linux/Dockerfile    # Path to Linux Dockerfile
          format: sarif
          output-file: hadolint-results-linux.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results-linux.sarif
          wait-for-processing: true

  hadolint_macos_dockerfile:
    name: Run hadolint scanning for macOS Dockerfile
    runs-on: macos-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      # Similar steps as above with necessary changes for macOS Dockerfile
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint for macOS Dockerfile
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./macos/Dockerfile    # Path to macOS Dockerfile
          format: sarif
          output-file: hadolint-results-macos.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results-macos.sarif
          wait-for-processing: true

  hadolint_windows_dockerfile:
    name: Run hadolint scanning for Windows Dockerfile
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      # Similar steps as above with necessary changes for Windows Dockerfile
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint for Windows Dockerfile
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./windows/Dockerfile    # Path to Windows Dockerfile
          format: sarif
          output-file: hadolint-results-windows.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results-windows.sarif
          wait-for-processing: true
