name: Push Image - MacOS

on:
  release:
    types: [published]

jobs:
  build-and-push-macos:
    name: Build and Push - MacOS
    runs-on: macos-latest

    outputs:
      release_version: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./macos/Dockerfile
          push: true
          tags: archblood/humhub-docker:${{ github.event.release.tag_name }}
