name: Push Image - Windows

on:
  release:
    types: [published]

jobs:
  build-and-push-windows:
    name: Build and Push - Windows
    runs-on: windows-latest

    outputs:
      release_version: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t archblood/humhub-docker:${{ github.event.release.tag_name }} -f windows/Dockerfile .
          # Update the path if your Windows Dockerfile is located elsewhere

      - name: Push Docker image to Docker Hub
        run: |
          docker push archblood/humhub-docker:${{ github.event.release.tag_name }}
