name: Docker Scout Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --file /src/Dockerfile \
            --tag humhub-docker:latest \
            --output type=docker \
            .

      - name: Install Docker Scout CLI
        run: |
          curl -sSL https://github.com/docker/scout-cli/releases/download/v0.3.0/scout-linux-amd64 -o /usr/local/bin/scout
          chmod +x /usr/local/bin/scout

      - name: Run Docker Scout Analysis
        run: |
          cd /src
          scout analyze humhub-docker:latest --output json > scan-results.json

      - name: Upload Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: scan-results.json
