name: Docker Scout Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Authenticate to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Dockerfile

      - name: Install Docker Scout CLI
        if: github.event_name != 'pull_request'
        run: |
          curl -sSL https://github.com/docker/scout-cli/releases/download/v0.3.0/scout-linux-amd64 -o /usr/local/bin/scout
          chmod +x /usr/local/bin/scout

      - name: Run Docker Scout Analysis
        if: github.event_name != 'pull_request'
        run: |
          cd src
          scout analyze ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }} --output json > scan-results.json

      - name: Upload Scan Results
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: src/scan-results.json
