name: Dockerfile Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Validate Dockerfile
        id: build
        run: |
          docker build --platform=linux/amd64 -t humhub-test -f Dockerfile .
          echo "::set-output name=image_name::humhub-test"

      - name: Check Docker build status
        run: |
          docker inspect ${{ steps.build.outputs.image_name }} || true

      - name: Verify Docker image
        run: |
          docker run --rm ${{ steps.build.outputs.image_name }} php -v || echo "PHP verification failed"
          docker run --rm ${{ steps.build.outputs.image_name }} apache2 -v || echo "Apache verification failed"

      - name: Cleanup
        run: |
          docker image rm ${{ steps.build.outputs.image_name }} || true
