name: Test Dockerfile

on:
  push:
    paths:
      - 'src/Dockerfile'
      - 'src/crontab'
  pull_request:
    paths:
      - 'src/Dockerfile'
      - 'src/crontab'
    branches:
      - main

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU (not needed on Windows/macOS)
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx (for Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v1

      - name: Install Docker (for macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install --cask docker

      - name: Validate Dockerfile
        id: build
        run: |
          docker build -t humhub-test -f src/Dockerfile .
          echo "IMAGE_NAME=humhub-test" >> $GITHUB_ENV || echo "::set-env name=SKIP_WINDOWS::true"

      - name: Check Docker build status
        if: ${{ matrix.os != 'windows-latest' && env.SKIP_WINDOWS != 'true' }}
        run: |
          docker inspect $IMAGE_NAME || true

      - name: Verify Docker image
        if: ${{ matrix.os != 'windows-latest' && env.SKIP_WINDOWS != 'true' }}
        run: |
          docker run --rm $IMAGE_NAME php -v || echo "PHP verification failed"
          docker run --rm $IMAGE_NAME apache2 -v || echo "Apache verification failed"

      - name: Copy crontab
        run: |
          cp src/crontab /tmp/crontab

      - name: Check crontab
        run: |
          docker run --rm -v /tmp/crontab:/etc/cron.d/humhub-cron $IMAGE_NAME bash -c 'chmod 0644 /etc/cron.d/humhub-cron && cat /etc/cron.d/humhub-cron' || echo "Crontab verification failed"

      - name: Cleanup
        run: |
          docker image rm $IMAGE_NAME || true
