name: Dockerfile Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Validate Dockerfile
        id: build
        run: |
          docker build --platform=linux/amd64 -t humhub-test -f Dockerfile .
          echo "IMAGE_NAME=humhub-test" >> $GITHUB_ENV

      - name: Check Docker build status
        run: |
          docker inspect $IMAGE_NAME || true

      - name: Verify Docker image
        run: |
          docker run --rm $IMAGE_NAME php -v || echo "PHP verification failed"
          docker run --rm $IMAGE_NAME apache2 -v || echo "Apache verification failed"

      - name: Copy crontab
        run: |
          cp crontab /tmp/crontab

      - name: Check crontab
        run: |
          docker run --rm -v /tmp/crontab:/etc/cron.d/humhub-cron $IMAGE_NAME bash -c 'chmod 0644 /etc/cron.d/humhub-cron && cat /etc/cron.d/humhub-cron' || echo "Crontab verification failed"

      - name: Cleanup
        run: |
          docker image rm $IMAGE_NAME || true
