name: Dockerfile Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Validate Dockerfile
        run: docker build -t humhub-test -f Dockerfile .
        continue-on-error: true

      - name: Check Docker build status
        run: docker inspect humhub-test || true

      - name: Verify Docker image
        run: |
          docker run --rm humhub-test php -v || exit 1
          docker run --rm humhub-test apache2 -v || exit 1
