name: Docker Image Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: sudo docker build -t greenmeteor/humhub-image .

      - name: Test Docker image
        run: |
          sudo docker run --rm greenmeteor/humhub-image echo "Docker image test successful"
