name: Test Dockerfile

on:
  push:
    paths:
      - 'src/Dockerfile'
      - 'src/crontab'
  pull_request:
    paths:
      - 'src/Dockerfile'
      - 'src/crontab'
    branches:
      - main

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Validate Dockerfile
        id: build
        run: |
          docker build -t humhub-test -f src/Dockerfile .

      - name: Check Docker build status
        run: |
          docker inspect humhub-test

      - name: Verify Docker image
        run: |
          docker run --rm humhub-test php -v || echo "PHP verification failed"
          docker run --rm humhub-test apache2 -v || echo "Apache verification failed"

      - name: Copy crontab
        run: |
          cp src/crontab /tmp/crontab

      - name: Check crontab
        run: |
          docker run --rm -v /tmp/crontab:/etc/cron.d/humhub-cron humhub-test bash -c 'chmod 0644 /etc/cron.d/humhub-cron && cat /etc/cron.d/humhub-cron' || echo "Crontab verification failed"

      - name: Cleanup
        run: |
          docker image rm humhub-test || true
