name: Docker Image Test

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Setup Docker Buildx
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name mybuilder
          docker buildx use mybuilder

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t greenmeteor/humhub-image .

      - name: Test Docker image
        run: |
          docker run --rm greenmeteor/humhub-image echo "Docker image test successful"
