name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 10 * * 4'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    outputs:
      release-tag: ${{ steps.set_release_tag.outputs.release_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release tag as output
        id: set_release_tag
        run: echo "::set-output name=release_tag::${{ github.event.release.tag_name }}"

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/archblood/humhub-docker:${{ github.event.release.tag_name }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/archblood/humhub-docker:${{ github.event.release.tag_name }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
